site_name: Scores Verification Package

plugins:
  - mkdocstrings


theme:
    name: readthedocs
    highlightjs: true

nav:
  - Home: index.md  
  - User Guide: userguide.md
  - Contributor Guide: contributing.md
  - Data Guide: data.md
  - API reference: api.md
